name: create-release-tag

on:
  workflow_dispatch: ~
  
jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create "release" Tag
        run: |
          git tag -f release
          git push -f origin release
