name: system-test-notification

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  notify:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    # This job runs only if the pull request is from a forked repository.
    if: github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Add comment
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: context.issue.number,
              body: `
            > **Warning**
            > System-tests will not be executed for this PR because it is from a forked repository. 
            But it will still create a successful system-test status check.
              `
            });
