name: heavy-test

on:
  pull_request: 
  issue_comment:
    types:
      - created

jobs:
  heavy-test:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
#    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/test')}}
    steps:
      - run: echo '${{ toJSON(github.event) }}'
      - run: echo "Hello"
      - run: echo '${{ secrets.FAKE_SECRET }}'

      - name: Save the PR number in an artifact
        env:
          PR_NUM: ${{ github.event.number }}
        run: echo $PR_NUM > pr_num.txt

      - name: Upload the PR number
        uses: actions/upload-artifact@v2
        with:
          name: pr_num
          path: ./pr_num.txt
#
#      - name: set status
#        uses: actions/github-script@v6
#        with:
#          script: |
#
#            const { repo, owner } = context.repo
#            await github.rest.issues.createComment({
#              owner,
#              repo,
#              issue_number: context.issue.number,
#              body: "Hello from GitHub Actions"
#            });
            
            
#            function sleep(ms) {
#              return new Promise(resolve => setTimeout(resolve, ms));
#            }
#
#            const { repo, owner } = context.repo
#            const pullRequest = await github.rest.pulls.get({
#              owner,
#              repo,
#              pull_number: context.issue.number,
#            });
#            const sha = pullRequest.data.head.sha
#
#            console.log(context)
#
#            await github.rest.repos.createCommitStatus({
#              owner,
#              repo,
#              sha,
#              state: "pending",
#              context: `${context.workflow} / ${context.job}`
#            });
#
#            await sleep(5000)
#
#            await github.rest.repos.createCommitStatus({
#              owner,
#              repo,
#              sha,
#              state: "success",
#              context: `${context.workflow} / ${context.job}`
#            });
