name: test

on:
  pull_request:
  push:
    branches:
      - main

# Cancel previous runs only on pull requests
concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ !!github.head_ref }}

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          sleep 300
          echo "Running tests"
          echo "Done"
